site_name: 'NatureForm Documentation'
site_url: 'https://natureform.github.io/NatureForm_Docs.github.io/' 

theme:
  name: material
  features:
    - navigation.tabs

nav:
  - 'Home': 'Home.md'
  - 'Frontend':
    - '2D Physics': 'Frontend/2dPhysics.md'
    - 'Floorplan Configurator': 'Frontend/FloorplanConfigurator.md'
    - 'Framework': 'Frontend/Framework.md'
    - 'Model Configurator': 'Frontend/ModelConfigurator.md'
    - 'Silhouette Extractor': 'Frontend/SilhouetteExtractor.md'
    - 'Three.js': 'Frontend/ThreeJS.md'
  - 'Fertigung':
    - 'Maschinen': 'Fertigung/Maschinenvergleich.md'
  - 'Marktstrategie & Analyse': 
    - 'Marktstrategie & Analyse': 'Marktstrategie & Analyse/Marktanalyse.md'
    - 'Kundenbedeurfnisse': 'Marktstrategie & Analyse/Kundenbeduerfnisse.md'
    - 'Konkurrenzanalyze': 'Marktstrategie & Analyse/Konkurrenzanalyze'
    - 'Zielgruppe': 'Marktstrategie & Analyse/Zielgruppe'
